dbAlias: "cbs"
tables:
  - "t_withhold_record"
  - "t_repay_apply"
  - "t_paid_guarantee_fee_statistics"
  - "t_repay_record"
  - "t_loan_order"
  - "t_paid_guarantee_fee_flow_statistics"
  - "t_credit_order"
  - "t_guarantee_fee_statistics"

sources:
  - instanceName: "rds-cbs-zzx"
    serverId: "80001001-80001999"
    host: "rm-wz9x5jv280wa9it72.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_zzx"
    password: "pkOOPWu&Eqv8eiTM"
    fbNo: "ZZX"
    dbName: "cbs"
  - instanceName: "rds-cbs-qhhf"
    serverId: "80002001-80002999"
    host: "rm-wz9d84kss8d5y144h.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_qhhf_cbs"
    password: "!9RZB3LvU!yjRLX"
    fbNo: "QHHF"
    dbName: "cbs"
  - instanceName: "rds-cbs-hr"
    serverId: "80003001-80003999"
    host: "rm-wz91ph70m5t13xm90.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_hr_cbs"
    password: "CHIe4Wj0QgWJdlQI"
    fbNo: "HR"
    dbName: "cbs"
  - instanceName: "rds-cbs-hnyc"
    serverId: "80004001-80004999"
    host: "rm-wz93pv334dobukq37.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_hnyc"
    password: "e$@^CN7Sb(rIE9%XIsx"
    fbNo: "HNYC"
    dbName: "cbs"
  - instanceName: "rds-cbs-zkhz"
    serverId: "80005001-80005999"
    host: "rm-wz96fm2gst9np7567.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_zkhz"
    password: "L2T+@MrO&Qa8GTb209O"
    fbNo: "ZKHZ"
    dbName: "cbs"
  - instanceName: "rds-cbs-hbhs"
    serverId: "80006001-80006999"
    host: "rm-wz9qcb8w89qkz871l.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_kangzhi_cbs"
    password: "AB1ZQk8vry6x7fOM"
    fbNo: "HBHS"
    dbName: "hbhs_cbs"
  - instanceName: "rds-cbs-hnxh"
    serverId: "80007001-80007999"
    host: "rm-wz90efuq25f193661.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_kangzhi_cbs"
    password: "AB1ZQk8vry6x7fOM"
    fbNo: "HNXH"
    dbName: "hnxh_cbs"
  - instanceName: "rds-cbs-yhx"
    serverId: "80008001-80008999"
    host: "rm-wz9e40n2z5h30w52m.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_xn"
    password: "H05WqY8wWgDI13"
    fbNo: "YHX"
    dbName: "cbs"
