dbAlias: "baowenchaifen"
tables:
  - "t_pd01e_repay_stat60_sub"

sources:
  - instanceName: "rds-bwcf-risk"
    serverId: "80201001-80201999"
    host: "rm-wz9eng2ombrkh4695.mysql.rds.aliyuncs.com"
    port: 3306
    username: "dm_binlog"
    password: "8trPD^TiefnAxk6h"
    fbNo: "JLY"
    dbName: "baowenchaifen"
