dbAlias: "pls"
tables:
  - "t_repay_plan_detail"

sources:
  - instanceName: "rds-pls-zzx"
    serverId: "80501001-80501999"
    host: "rm-wz98qflbe20fuj44f.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_zzx"
    password: "pkOOPWu&Eqv8eiTM"
    fbNo: "ZZX"
    dbName: "pls"
  - instanceName: "rds-pls-qhhf"
    serverId: "80502001-80502999"
    host: "rm-wz9yx9a6w3c421g2z.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_qhhf"
    password: "ZSxc1$W7b$k1&Bs@"
    fbNo: "QHHF"
    dbName: "pls"
  - instanceName: "rds-pls-hr"
    serverId: "80503001-80503999"
    host: "rm-wz9cq58qvsd3e442v.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_hr"
    password: "6pH&Wf%5AaLeCFni"
    fbNo: "HR"
    dbName: "pls"
  - instanceName: "rds-pls-yhx"
    serverId: "80504001-80504999"
    host: "rm-wz9fu6pw0md82e2lj.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_xn"
    password: "H05WqY8wWgDI13"
    fbNo: "YHX"
    dbName: "pls"
  - instanceName: "rds-pls-hbhs"
    serverId: "80505001-80505999"
    host: "rm-wz9p5u9a79ye30f54.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_kangzhi"
    password: "U8pCXHtEmuFOFzDX"
    fbNo: "HBHS"
    dbName: "hbhs_pls"
  - instanceName: "rds-pls-hnxh"
    serverId: "80506001-80506999"
    host: "rm-wz9p5u9a79ye30f54.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_kangzhi"
    password: "U8pCXHtEmuFOFzDX"
    fbNo: "HNXH"
    dbName: "hnxh_pls"
  - instanceName: "rds-pls-hnyc"
    serverId: "80507001-80507999"
    host: "rm-wz9g69v16j9dvh00c.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_hnyc"
    password: "e$@^CN7Sb(rIE9%XIsx"
    fbNo: "HNYC"
    dbName: "pls"
  - instanceName: "rds-pls-zkhz"
    serverId: "80508001-80508999"
    host: "rm-wz95xy84bszurl5o2.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_zkhz"
    password: "L2T+@MrO&Qa8GTb209O"
    fbNo: "ZKHZ"
    dbName: "pls"
