dbAlias: "fxcz"
tables:
  - "t_loan_balance"

sources:
  - instanceName: "rds-fxcz-zzx"
    serverId: "80301001-80301999"
    host: "rm-wz98qflbe20fuj44f.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_zzx"
    password: "pkOOPWu&Eqv8eiTM"
    fbNo: "ZZX"
    dbName: "fxcz"
  - instanceName: "rds-fxcz-qhhf"
    serverId: "80302001-80302999"
    host: "rm-wz9yx9a6w3c421g2z.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_qhhf"
    password: "ZSxc1$W7b$k1&Bs@"
    fbNo: "QHHF"
    dbName: "fxcz"
  - instanceName: "rds-fxcz-hr"
    serverId: "80303001-80303999"
    host: "rm-wz9cq58qvsd3e442v.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_hr"
    password: "6pH&Wf%5AaLeCFni"
    fbNo: "HR"
    dbName: "fxcz"
  - instanceName: "rds-fxcz-yhx"
    serverId: "80304001-80304999"
    host: "rm-wz9fu6pw0md82e2lj.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_xn"
    password: "H05WqY8wWgDI13"
    fbNo: "YHX"
    dbName: "fxcz"
  - instanceName: "rds-fxcz-hbhs"
    serverId: "80305001-80305999"
    host: "rm-wz9p5u9a79ye30f54.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_kangzhi"
    password: "U8pCXHtEmuFOFzDX"
    fbNo: "HBHS"
    dbName: "hbhs_fxcz"
  - instanceName: "rds-fxcz-hnxh"
    serverId: "80306001-80306999"
    host: "rm-wz9p5u9a79ye30f54.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_kangzhi"
    password: "U8pCXHtEmuFOFzDX"
    fbNo: "HNXH"
    dbName: "hnxh_fxcz"
  - instanceName: "rds-fxcz-hnyc"
    serverId: "80307001-80307999"
    host: "rm-wz9g69v16j9dvh00c.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_hnyc"
    password: "e$@^CN7Sb(rIE9%XIsx"
    fbNo: "HNYC"
    dbName: "fxcz"
  - instanceName: "rds-fxcz-zkhz"
    serverId: "80308001-80308999"
    host: "rm-wz95xy84bszurl5o2.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_zkhz"
    password: "L2T+@MrO&Qa8GTb209O"
    fbNo: "ZKHZ"
    dbName: "fxcz"
