dbAlias: "cap"
tables:
  - "t_cap_repay_plan_detail"
  - "t_repay_apply_info"
  - "t_claim_info"
  - "t_cap_derivative_history"
  - "t_loan_apply_info"
  - "t_credit_apply_record"

sources:
  - instanceName: "rds-cap-zzx"
    serverId: "80101001-80101999"
    host: "rm-wz915s1pyl3un2ud0.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_zzx"
    password: "pkOOPWu&Eqv8eiTM"
    fbNo: "ZZX"
    dbName: "cap"
  - instanceName: "rds-cap-qhhf"
    serverId: "80102001-80102999"
    host: "rm-wz9660m9a598n566c.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_qhhf_cap"
    password: "EVa9FysQfb4#rYc"
    fbNo: "QHHF"
    dbName: "cap"
  - instanceName: "rds-cap-hr"
    serverId: "80103001-80103999"
    host: "rm-wz920fj19jspo5ap1.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_hr_cap"
    password: "FUXkgc3jjfnpvyRL"
    fbNo: "HR"
    dbName: "cap"
  - instanceName: "rds-cap-hnyc"
    serverId: "80104001-80104999"
    host: "rm-wz906w12xm2m43p06.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_hnyc"
    password: "e$@^CN7Sb(rIE9%XIsx"
    fbNo: "HNYC"
    dbName: "cap"
  - instanceName: "rds-cap-zkhz"
    serverId: "80105001-80105999"
    host: "rm-wz9j477ljg1142sy5.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_zkhz"
    password: "L2T+@MrO&Qa8GTb209O"
    fbNo: "ZKHZ"
    dbName: "cap"
  - instanceName: "rds-cap-hbhs"
    serverId: "80106001-80106999"
    host: "rm-wz9n0335j85oap2zr.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_kangzhi_cap"
    password: "phjNKNzO3vasR1kQ"
    fbNo: "HBHS"
    dbName: "hbhs_cap"
  - instanceName: "rds-cbs-hnxh"
    serverId: "80107001-80107999"
    host: "rm-wz94p13c4q107e0iv.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_kangzhi_cap"
    password: "phjNKNzO3vasR1kQ"
    fbNo: "HNXH"
    dbName: "hnxh_cap"
  - instanceName: "rds-cbs-yhx"
    serverId: "80108001-80108999"
    host: "rm-wz9e40n2z5h30w52m.mysql.rds.aliyuncs.com"
    port: 3306
    username: "binlog_xn"
    password: "H05WqY8wWgDI13"
    fbNo: "YHX"
    dbName: "cap"
